project_id = "fhfmwdbousoycutlhvjh"

[functions.task-dispatcher]
verify_jwt = false

[functions.jac-dispatcher]
verify_jwt = false

[functions.jac-research-agent]
verify_jwt = false

[functions.jac-save-agent]
verify_jwt = false

[functions.jac-search-agent]
verify_jwt = false

[functions.slack-incoming]
verify_jwt = false

[functions.jac-code-agent]
verify_jwt = false
